version: '2'
services:
  web:
    restart: unless-stopped
    container_name: monitor-custom-test
    image: monitor-custom-test
    networks:
      - custom
    ports:
      - "6669:6669"
    volumes:
      - /data/monitoring/latest/RData:/app/data
      - /var/log/monitor-custom/test/app:/app/logs
      - /var/cache/monitor-qc-report/test/app:/app/output

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.69.0/24
          gateway: 172.66.69.1

