FROM mazamascience/pwfslsmoke:v1.0.20
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>

#######################################################################
# For the monitor-custom app
RUN install2.r --error \
    jug \
    MazamaWebUtils \
    ggplot2
    
# Install latest development versions of packages
RUN installGithub.r \
    MazamaScience/PWFSLSmoke \
    MazamaScience/PWFSLSmokePlots

#######################################################################
# jug instance configuration
#
# ProxyPass settings are defined in:  /etc/apache2/sites-enabled/default-ssl.conf
# 
# On haze, we will adopt following protocol for ProxyPass settings:
#  * all monitoring services will be on ports in the range 6600-6699
#  * each unique service will have a block of ports from 66#0-66#9
#  * port 66#0 is reserved for the "latest" version
#  * port 66#X is reseved for version X of a service
#  * port 66#9 is reserved for a "test" version
#
# The block of ports 6660-6669 is reserved for the 'monitor-custom' service
ENV JUG_HOST 0.0.0.0
ENV JUG_PORT 6669

EXPOSE 6669

#######################################################################
# app
#
# Setup for haze.airfire.org

# Environment variables ---------------

# path and cache (see apache ProxyPass settings)
ENV SERVICE_PATH monitor-custom/test
ENV CACHE_DIR output
ENV CACHE_SIZE 100

# mounted directories
ENV DATA_DIR /app/data
ENV LOG_DIR /app/logs

# Set up the app ----------------------

WORKDIR /app

# jug app and all associated files
COPY monitor-custom-app.R /app
COPY output /app/output
COPY R /app/R

# Start the jug app when the image starts up
CMD [ "Rscript", "/app/monitor-custom-app.R" ]

