FROM mazamascience/pwfslsmoke:1.2.113
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>

#######################################################################
# For the monitor-custom app
RUN install2.r --error \
    rmarkdown \
    ggplot2 \
    ggthemes \
    beakr \
    MazamaCoreUtils

# Install latest development versions of packages
RUN installGithub.r \
    MazamaScience/PWFSLSmokePlots

#######################################################################
# beakr instance configuration
#
# ProxyPass settings are defined in:  /etc/apache2/sites-enabled/default-ssl.conf
#
# On the host, we will adopt following protocol for ProxyPass settings:
#  * all monitoring services will be on ports in the range 6600-6699
#  * each unique service will have a block of ports from 66#0-66#9
#  * port 66#0 is reserved for the "latest" version
#  * port 66#X is reseved for version X of a service
#  * port 66#9 is reserved for a "test" version
#
# The block of ports 6660-6669 is reserved for the 'monitor-custom' service
ENV BEAKR_HOST 0.0.0.0
ENV BEAKR_PORT 6669

EXPOSE 6669

#######################################################################
# app
#
# Setup for AWS hosts

# Environment variables ---------------

# path and cache (see apache ProxyPass settings)
ENV SERVICE_PATH monitor-custom/test

# mounted directories
ENV DATA_DIR /app/data
ENV LOG_DIR /app/logs
ENV CACHE_DIR /app/output
ENV CACHE_SIZE 10

# Set up the app ----------------------

WORKDIR /app

# beakr app and all associated files
COPY R /app/R

CMD [ "Rscript", "/app/R/monitor-custom-app.R" ]
